# Generated by Django 5.2.4 on 2025-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iamge',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
