# Generated by Django 5.2.4 on 2025-08-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iamge',
            new_name='image',
        ),
    ]
